# Generated by Django 2.2.26 on 2022-03-15 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220314_0539'),
        ('dashboard', '0002_auto_20220314_1401'),
    ]

    operations = [
    ]
