# Generated by Django 2.2.26 on 2022-03-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_merge_20220315_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='subscription',
            field=models.IntegerField(null=True, verbose_name='Subscription'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='app',
            field=models.IntegerField(verbose_name='App'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.IntegerField(default=1, verbose_name='Plan'),
            preserve_default=False,
        ),
    ]
